### ISSUE TITLE
代码无法导入一些模块？

### ISSUE THREAD

**Issue by 20174285** [ZhouCX117/UAED_MuGE#24]
你好，请问这个代码为啥无法跑通？
<img width="666" alt="2" src="https://github.com/ZhouCX117/UAED/assets/54831357/d44b269d-0f9c-4ce9-b68a-bad5173d68b1">
from efficientnet_pytorch import EfficientNet
from efficientnet_pytorch.utils import url_map, url_map_advprop, get_model_params
这几行代码从哪儿导入呢？代码中没找到

**Comment by ZhouCX117** [comment]
你好，pip install efficientnet_pytorch就好。

**Comment by 20174285** [comment]
> 你好，pip install efficientnet_pytorch就好。

谢谢啦，明白了
