### ISSUE TITLE
作者你好，关于将EfficientNet编码器分为5个阶段送入Unet++是根据每阶段输出的图像大小决定的吗？

### ISSUE THREAD

**Issue by TIVEN-Z** [ZhouCX117/UAED_MuGE#25]
def get_stages(self):
        return [
            nn.Identity(),
            nn.Sequential(self._conv_stem, self._bn0, self._swish),
            self._blocks[: self._stage_idxs[0]],
            self._blocks[self._stage_idxs[0]: self._stage_idxs[1]],
            self._blocks[self._stage_idxs[1]: self._stage_idxs[2]],
            self._blocks[self._stage_idxs[2]:],
        ]

**Comment by ZhouCX117** [comment]
您好，是的，这块我没有做修改，直接参照的https://github.com/qubvel/segmentation_models.pytorch里面源码
