### ISSUE TITLE
能否提供Multicue数据集的测试集与训练集的划分文件

### ISSUE THREAD

**Issue by zhoujh2020** [ZhouCX117/UAED_MuGE#26]
我在您提供的Multicue数据集上按照您在论文中描述的方式做了三次随机划分训练集和测试集，并使用您的代码进行训练，然而结果却远远落后于您提供的数据，我们认为这可能受到划分的数据集的影响，您能否提供对应的划分文件帮助我们获得更优秀的数据呢？如果可以我将非常感谢！

**Comment by ZhouCX117** [comment]
@zhoujh2020 @Star-xing1 可以给我个邮箱，我转发给你

**Comment by ZhouCX117** [comment]
@shiwanghaha 已发送

**Comment by sfg-oss** [comment]
你好，可以也给我一份吗，我的邮箱是3227073548@qq.com,谢谢您！
