### ISSUE TITLE
test_muge.py运行出错

### ISSUE THREAD

**Issue by zjl603** [ZhouCX117/UAED_MuGE#29]
作者你好，我在尝试运行test_muge.py，但是遇到了一些错误：

在使用您提供的MUGE权重best_test_saved_weights.pth时，
model.load_state_dict(checkpoint['state_dict'])报错：KeyError: 'state_dict'，
以及RuntimeError: Error(s) in loading state_dict for Mymodel: Missing key(s) in state_dict: "encoder._conv_stem.weight"......

请问best_test_saved_weights.pth与代码中的Mymodel是否是匹配的？
另外有一处引用错误，找不到data_loader_one_random_drx文件。

非常感谢您的支持！！

**Comment by ZhouCX117** [comment]
您好，Mymodel是训练好的checkpoint，不是best_test_saved_weights.pth，我已上传在BSDS上训练好的checkpoint，麻烦下载。data_loader_one_random_drx可以换成data_loader_one_random_uncert，test数据集的加载方式都一致。

**Comment by zjl603** [comment]
已解决，非常感谢！
