### ISSUE TITLE
The parameters and running speed

### ISSUE THREAD

**Issue by ForawardStar** [ZhouCX117/UAED_MuGE#30]
Hello, wonderful project! I would like to know the total parameter amount and running speed of both UAED and MuGE?

**Comment by ZhouCX117** [comment]
Hi, sorry for the late reply. The integration of granularity doesn't increase much parameter amount and inference time for one granularity, you can refer to 'Computational cost' in the UAED paper.

**Comment by ForawardStar** [comment]
如果需用MuGE输出多种不同的边缘检测结果的话，是不是速度就要相应地减少相同的倍数，比如输出11个边缘图，速度就要比原先慢11倍

**Comment by Sphinxxx233** [comment]
想问一下nms的代码，自己试了几种和论文中打不太一样，谢谢！

**Comment by ZhouCX117** [comment]
不同的边缘图生成过程中encoder得到特征的过程可以复用，但是decoder过程需要走多次
