### ISSUE TITLE
UAED显存溢出

### ISSUE THREAD

**Issue by yx-yyds** [ZhouCX117/UAED_MuGE#32]
你好，为什么我在训练UAED的时候显存占用量会不断增加，直至最后显示显存不足，我把batch size设为2，初始时显示只占用6GB左右的显存。

**Comment by ZhouCX117** [comment]
你好，没有遇到这个问题，有修改代码什么地方吗？

**Comment by yx-yyds** [comment]
train_root="/data/zhoucaixia/workspace/UD_Edge/"  -> train_root = "Z:/yx/experiments/UAED_MuGE-main"
copyfile(join(train_root,"train",file_name),join(TMP_DIR,file_name)) -> copyfile(join(train_root, file_name), join(TMP_DIR, file_name))
parser.add_argument('--gpu', default='0', type=str, help='GPU ID') -> parser.add_argument('--gpu', default='0', type=str, help='GPU ID')
我就改了这些，其他的就是和数据路径有关的代码

**Comment by ZhouCX117** [comment]
你好，我看你是windows系统跑的程序，麻烦排查下是不是windows造成的，我跑实验过程中没有遇到过这个问题。
