### ISSUE TITLE
some little errors in the code

### ISSUE THREAD

**Issue by senliontec** [ZhouCX117/UAED_MuGE#34]
A very excellent work, but with some little errors in the code.

1. in train_muge.py file
 
    line 18: from models.model_cls import VGG16

     'models.model_cls' does not exist in the code

2. in test_muge.py file

    line 16: from models.sigma_logit_unetpp_alpha_ffthalf_feat import Mymodel

   I can't find the correct module.

Thanks for your work, maybe the imporovement of this issue will make the code more readable.

**Comment by ZhouCX117** [comment]
Thanks for your feedback. I checked the code and found that the directory name was wrong. Changing the directory name "model" to "models" solved the problem.
