### ISSUE TITLE
Inference on our own data

### ISSUE THREAD

**Issue by RoberAlcaraz** [ZhouCX117/UAED_MuGE#35]
Hi,

I’m currently trying to use the project for inference on my own data, but the process is a bit unclear. Could you please provide some guidance on the following?

    1. What steps do I need to follow to train the models with my own data? Specifically, which files/paths should I modify?
    2. Is it possible to make inferences directly using the current checkpoints? If so, could you explain how?

Thank you in advance for your help!

**Comment by ZhouCX117** [comment]
Thanks for your attention.
You can inference with the provided BSDS checkpoint. 
1. git clone git@github.com:ZhouCX117/UAED_MuGE.git, and mv directory 'model' to 'models';
2. download pretrained BSDS checkpoint from the google disk (https://drive.google.com/file/d/15NucsEeHAFwo5O2s11pMR1BikoUtiuUX/view);
3. Revise 'test_muge.py' line2 to your workspace directory,  line26 to your test image directory, line 37 to your downloaded model checkpoint directory, line 45 to your save directory;
4. Save all your test image names into a txt file, every line an image name. Then revise line32 with this txt file directory.

I hope this can help you!

**Comment by ZhouCX117** [comment]
@john09282922 Thanks for your focus. I am sorry that I mistake 'test_muge.py' and 'test_uaed.py'.

First, git clone [git@github.com](mailto:git@github.com):ZhouCX117/UAED_MuGE.git, and mv directory 'model' to 'models';

1. Test using UAED.
(1) download pretrained BSDS checkpoint from the google disk (https://drive.google.com/file/d/1nv2_TZRyiQh5oU9TnGMzu313OrspD2l5/view?usp=sharing);
(2) Revise 'test_uaed.py' line2 to your workspace directory, line26 to your test image directory, line 37 to your downloaded model checkpoint directory, line 45 to your save directory;
(3) Save all your test image names into a txt file, every line an image name. Then revise line32 with this txt file directory.

2. Test using MuGE
 (1) download pretrained BSDS checkpoint from the google disk (https://drive.google.com/file/d/15NucsEeHAFwo5O2s11pMR1BikoUtiuUX/view);
(2) Revise 'test_muge.py' line4 to your workspace directory, line29 to your test image directory, line 39 to your downloaded model checkpoint directory, line 46 to your save directory;
(3) Save all your test image names into a txt file, every line an image name. Then revise line34 with this txt file directory.

If you encounter any questions, please feel free to contact me.
